/* Catalogue Witchfire — chiffres repris du wiki (consulté le 5 octobre 2026).
   https://witchfire.wiki.gg — Elements, Weapons, Spells, Magical Items, Rosary, Arcana, Gnosis.
   Un objet « elements » ouvre la pioche d'arcanes. « applies » décrit le malus réellement infligé. */
(function (root) {
  const EL = {
    fire: { id: "fire", name: "Feu", ailment: "Brûlure", verb: "brûle" },
    earth: { id: "earth", name: "Terre", ailment: "Putréfaction", verb: "pourrit" },
    air: { id: "air", name: "Air", ailment: "Choc", verb: "électrocute" },
    water: { id: "water", name: "Eau", ailment: "Gel", verb: "gèle" },
  };

  const weapons = [
    w("hunger", "Hunger", "Canon à main", "medium", ["water"], 0, { damage: 38, crit: 1.14, stun: "très élevé", ads: 21, hip: 15, rof: 2.8, reload: 2.3, mag: 6, reserve: 84, mobility: "très haute" },
      ["M1 : une balle chargée par critique avant le rechargement, +60 % de dégâts.", "M2 : +10 % de dégâts supplémentaires par critique.", "M3 : le premier tir au corps après rechargement compte comme un critique. Si tous les tirs étaient critiques, la première balle gèle."],
      { freeze: { from: 3, reliable: 0.35, note: "Une seule balle de gel, et seulement après un chargeur entièrement critique." } },
      "Arme de départ de toutes les classes.", "https://witchfire.wiki.gg/wiki/Hunger"),
    w("echo", "Echo", "Fusil à pompe", "close", ["fire"], 0, { damage: 95, crit: 1.1, stun: "moyen", ads: 7, hip: 7, rof: 1.7, reload: 0.6, mag: 6, reserve: 40, mobility: "très haute", unwieldy: "shotgun", pellets: "6 plombs. Le wiki détaille 5 dégâts par plomb sur un ancien relevé ; la fiche actuelle indique 95." },
      ["M1 : les plombs explosent en différé et brûlent (+12,5 %, sensible aux perles). Un tir mortel repousse fort.", "M2 : l'explosion mortelle gagne en portée et brûle les voisins (+25 %).", "M3 : glisser recharge deux cartouches et donne +50 % de dégâts sur le coup suivant, 5 s."],
      { burn: { from: 1, bead: true, mag: { 1: 0.125, 2: 0.25, 3: 0.25 } } },
      "Recherche au miroir de l'atelier, Gnosis 0, sans coût.", "https://witchfire.wiki.gg/wiki/Echo"),
    w("angelus", "Angelus", "Fusil automatique", "medium", [], 0, { damage: 13, crit: 1.18, stun: "moyen", ads: 21, hip: 18, rof: 8.3, reload: 4, mag: 70, reserve: 420, mobility: "moyenne" },
      ["Pas d'élément. Cadence et chargeur pour tenir une ligne sans malus."],
      {}, "Recherche, Gnosis 0.", "https://witchfire.wiki.gg/wiki/Angelus"),
    w("psychopomp", "Psychopomp", "Fusil à pompe", "close", [], 1, { damage: 90, crit: 1.1, stun: "faible", ads: 9, hip: 9, rof: 4.3, reload: 0.6, mag: 10, reserve: 40, mobility: "très haute", unwieldy: "shotgun" },
      ["M1 : un kill à la mêlée chargée rend jusqu'à la moitié du chargeur.", "M2 : les tirs d'affilée sur la même cible gagnent 10 % de dégâts, jusqu'à +50 %.", "M3 : un kill recharge la mêlée.", "Huit plombs. Viser, s'accroupir ou glisser resserre le cône. Tirer coûte de l'endurance, sauf avec la perle Short Range. Les 0,6 s sont le temps d'une cartouche."],
      {}, "Recherche, 7 witchfire, Gnosis I.", "https://witchfire.wiki.gg/wiki/Psychopomp"),
    w("hailstorm", "Hailstorm", "Fusil de précision", "long", ["water"], 1, { damage: 160, crit: 1.4, stun: "moyen", ads: 67, hip: 15, rof: 0.8, reload: 4.8, mag: 5, reserve: 20, mobility: "très faible", unwieldy: "sniper" },
      ["M1 : chaque troisième critique d'affilée rend deux balles dans le chargeur, prises sur la réserve. Le rechargement ne remet pas le compteur à zéro.", "M2 : les critiques enchaînés réduisent le zoom et le recul, et améliorent la maniabilité. Une erreur ou un rechargement annule ce bonus.", "M3 : chaque troisième critique d'affilée lâche une onde de gel. Elle ne blesse pas : elle fige la cible et les ennemis proches. Un ennemi gelé subit +50 % de dégâts.", "Viser et tirer coûte de l'endurance. La perle Long Range retire ce coût."],
      { freeze: { from: 3, reliable: 0.45, note: "Onde de gel tous les trois critiques d'affilée. Le gel ignore les perles." } },
      "Recherche, 5 witchfire, Gnosis I.", "https://witchfire.wiki.gg/wiki/Hailstorm"),
    w("hangfire", "Hangfire", "Canon à main", "medium", ["fire"], 1, { damage: 38, crit: 1.1, stun: "moyen", ads: 19, hip: 15, rof: 2.2, reload: 3, mag: 6, reserve: 84, mobility: "très haute" },
      ["Élément Feu pour la pioche d'arcanes. Les tables de brûlure du wiki ne lui attribuent pas de magnitude propre : il ne compte pas comme source de Brûlure dans le calcul."],
      {}, "Recherche, 5 witchfire, Gnosis I.", "https://witchfire.wiki.gg/wiki/Hangfire"),
    w("hypnosis", "Hypnosis", "Fusil à verrou", "long", ["air"], 1, { damage: 40, crit: 1.28, stun: "moyen", ads: 36, hip: 20, rof: 0.9, reload: 4, mag: 10, reserve: 78, mobility: "moyenne" },
      ["M1 : viser charge la balle jusqu'au double de dégâts.", "M2 : le tir parfait, entre 1,3 et 1,45 s, quadruple les dégâts.", "M3 : au troisième tir parfait d'affilée, la chaîne inflige 50 % du tir puis un Choc dont les éclairs valent 30 % du tir. Ces chaînes de Mysterium ignorent les perles tant que le Choc n'est pas posé."],
      { shock: { from: 3, bead: false, first: 0.5, second: 0.25, ailmentFirst: 0.3, ailmentSecond: 0.15, note: "La chaîne du troisième palier vaut 50 % puis 25 % et ignore les perles. Le Choc posé ensuite est la ligne Hypnosis de la table : 30 % puis 15 %, sensible aux perles." } },
      "Recherche, sans coût, Gnosis I.", "https://witchfire.wiki.gg/wiki/Hypnosis"),
    w("frostbite", "Frostbite", "Fusil à verrou", "long", ["water"], 2, { damage: 77, crit: 1.24, stun: "élevé", ads: 46, hip: 26, rof: 0.8, reload: 3.5, mag: 6, reserve: 84, mobility: "moyenne" },
      ["Fort étourdissement et élément Eau. Le wiki ne publie pas de gel automatique : à coupler avec un sort d'Eau."],
      {}, "Recherche, Gnosis II.", "https://witchfire.wiki.gg/wiki/Frostbite"),
    w("basilisk", "Basilisk", "Fusil de précision", "long", ["fire"], 2, { damage: 60, crit: 1.4, stun: "moyen", ads: 36, hip: 20, rof: 1.1, reload: 4, mag: 10, reserve: 40, mobility: "faible", unwieldy: "sniper" },
      ["M1 : un critique allume la lunette 3 s. Regarder un ennemi à travers la lunette pose une Brûlure de +50 %, insensible aux perles.", "M2 : tirer sur une cible qui brûle prolonge la brûlure de 6 s et peut en écraser la magnitude.", "M3 : tuer un brûlé d'un critique passe la lunette à +75 % et à des ticks directs (environ 11 ticks, 87 dégâts dans le meilleur cas cité)."],
      { burn: { from: 1, bead: false, mag: { 1: 0.5, 2: 0.5, 3: 0.75 } } },
      "Recherche, 7 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Basilisk"),
    w("duelist", "Duelist", "Canon à main", "medium", ["fire"], 2, { damage: 25, crit: 1.14, stun: "faible", ads: 18, hip: 15, rof: 4.1, reload: 2.5, mag: 12, reserve: 168, mobility: "moyenne" },
      ["Cadence honnête et élément Feu. Absente des tables de magnitude : la Brûlure doit venir d'un sort, d'un anneau ou d'une autre arme."],
      {}, "Recherche, 7 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Duelist"),
    w("ricochet", "Ricochet", "Fusil automatique", "medium", ["air"], 2, { damage: 16, crit: 1.2, stun: "élevé", ads: 26, hip: 20, rof: 6.6, reload: 3.4, mag: 30, reserve: 270, mobility: "moyenne" },
      ["Élément Air. La page Éléments renvoie à la page de l'arme pour le détail des chaînes, sans pourcentage dans le tableau général."],
      { shock: { from: 1, bead: true, first: 0.3, second: 0.15, qualitative: true, note: "Choc attesté par l'élément et les guides, pourcentage de chaîne non repris dans le tableau général." } },
      "Recherche, 3 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Ricochet"),
    w("koschei", "Koschei", "Fusil automatique", "medium", ["earth"], 2, { damage: 20, crit: 1.2, stun: "faible", ads: 18, hip: 14, rof: 6.3, reload: 1, mag: 36, reserve: 396, mobility: "moyenne" },
      ["Se recharge seul, de plus en plus vite, même rangé.", "M1 : recharger vide l'endurance et lâche un essaim d'os qui pourrit. Trois charges, une par kill au tir principal.", "M2 : subir des dégâts recharge aussi l'essaim. Tirer sur un pourri prolonge la Putréfaction.", "M3 : six kills avant l'essaim augmentent le nombre d'éclats et la puissance."],
      { decay: { from: 1, bead: true, profile: "koschei" } },
      "Quête des os au miroir après le Gnosis II. Fragments à Velmorne.", "https://witchfire.wiki.gg/wiki/Koschei"),
    w("corpse-eater", "Corpse Eater", "Canon à main", "medium", ["earth"], 2, { damage: 25, crit: 1.14, stun: "moyen", ads: 14, hip: 10, rof: 3.6, reload: 2.2, mag: 12, reserve: 168, mobility: "très haute" },
      ["M2 : putréfaction au tir, puissance chiffrée surtout dans la synergie Trinité.", "Trinité avec Heart Eater et Soul Eater au Mysterium III : la putréfaction citée vaut 5 dégâts par tick pendant 26 ticks, et se propage."],
      { decay: { from: 2, bead: true, qualitative: true, note: "Applicateur Terre. Le seul total publié en clair est celui de la Trinité : 5 par tick, 26 ticks." } },
      "Coffre-fort des Outskirts, sur une caisse à gauche de l'escalier des récompenses.", "https://witchfire.wiki.gg/wiki/Corpse_Eater"),
    w("oracle", "Oracle", "Fusil de précision", "long", [], 2, { damage: 160, crit: 1.4, stun: "élevé", ads: 67, hip: 15, rof: 0.8, reload: 2, mag: 5, reserve: 20, mobility: "très faible", unwieldy: "sniper" },
      ["160 dégâts, critique 140 %, rechargement 2 s, étourdissement élevé. Pas d'élément : ce n'est pas une source de malus.", "M1 : chaque kill charge la lunette, jusqu'à trois tirs. Un tir chargé voit et traverse les murs. Un kill à travers un mur ne recharge pas la lunette, et les boucliers arrêtent le tir. Détruire un piège charge aussi.", "M2 : un ennemi gardé en visée est ralenti.", "M3 : rester en visée deux secondes sans tirer donne +50 % au coup suivant.", "Même coût d'endurance que Hailstorm, annulé par la perle Long Range. Ne blesse pas le corps du Golem, seulement son noyau."],
      {}, "Profondeurs de Velmorne, derrière la petite cascade au nord de la fontaine.", "https://witchfire.wiki.gg/wiki/Oracle"),
    w("cricket", "Cricket", "Pistolet-mitrailleur", "close", [], 3, { damage: 17, crit: 1.1, stun: "très faible", ads: 9, hip: 9, rof: 10, reload: 3, mag: 30, reserve: 330, mobility: "très haute" },
      ["Cadence de proche sans élément."],
      {}, "Recherche, 3 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Cricket"),
    w("midas", "Midas", "Fusil automatique", "medium", ["fire"], 3, { damage: 11, crit: 1.2, stun: "très faible", ads: 25, hip: 17, rof: 11.1, reload: 4, mag: 60, reserve: 540, mobility: "moyenne" },
      ["Tuyau à balles de feu pour les arcanes et pour nourrir un Bûcher ardent. Les tables ne lui donnent pas de Brûlure propre. Le Boucher peut le recevoir au départ ; les autres classes le recherchent."],
      {}, "Recherche, 12 witchfire, Gnosis III. Départ du Boucher.", "https://witchfire.wiki.gg/wiki/Midas"),
    w("nemesis", "Nemesis", "Fusil à levier", "medium", ["fire"], 3, { damage: 70, crit: 1.34, stun: "moyen", ads: 32, hip: 18, rof: 1.2, reload: 0.6, mag: 8, reserve: 80, mobility: "moyenne" },
      ["M3 : la troisième marque pose une Brûlure de +12,5 %, insensible aux perles. Rechargement très court (0,6 s)."],
      { burn: { from: 3, bead: false, mag: { 1: 0, 2: 0, 3: 0.125 } } },
      "Recherche, 15 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Nemesis"),
    w("all-seeing-eye", "All-Seeing Eye", "Fusil à verrou", "long", ["earth"], 3, { damage: 38, crit: 1.34, stun: "faible", ads: 32, hip: 18, rof: 1, reload: 4, mag: 6, reserve: 96, mobility: "faible" },
      ["Putréfaction légère mais longue : 2 dégâts par tick, 30 ticks, 60 au total en base."],
      { decay: { from: 1, bead: true, profile: "eye" } },
      "Recherche, 8 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/All-Seeing_Eye"),
    w("martyr", "Martyr", "Empaleur", "medium", [], 3, { damage: 20, crit: 1.2, stun: "faible", ads: 45, hip: 30, rof: 5, reload: 2.4, mag: 16, reserve: 224, mobility: "moyenne" },
      ["Marque une cible : les clous suivants la cherchent. Pas d'élément."],
      {}, "Coffre-fort de sorcière de Velmorne. Gnosis III et 15 000 pour dissiper. Récupérable sans tuer l'Exécuteur.", "https://witchfire.wiki.gg/wiki/Martyr"),
    w("fatum", "Fatum", "Pistolet-mitrailleur", "close", ["fire", "water", "air"], 3, { damage: 10, crit: 1.21, stun: "très faible", ads: 9, hip: 9, rof: 15.1, reload: 2.5, mag: 60, reserve: 460, mobility: "très haute" },
      ["M1 : chaque anneau actif après un rechargement post-kill vaut +10 % de dégâts, +40 % si les trois tournent.", "M2 : deux anneaux de la même couleur donnent 15 % de chance par balle d'appliquer Feu, Eau ou Air pour le reste du chargeur. Brûlure standard +25 %.", "M3 : trois anneaux identiques, 10 s d'endurance, de munitions ou de charges de sort léger infinies.", "La table des éléments crédite Fatum d'une chaîne de Choc à 75 % puis 37,5 % quand l'Air est posé."],
      {
        burn: { from: 2, bead: true, mag: { 1: 0, 2: 0.25, 3: 0.25 }, reliable: 0.15 },
        freeze: { from: 2, reliable: 0.15, note: "15 % de chance par balle si deux anneaux d'Eau sont alignés." },
        shock: { from: 2, bead: true, first: 0.75, second: 0.375, reliable: 0.15 },
      },
      "Trois orbes latents d'Irongate Castle, descellés à l'apothicaire.", "https://witchfire.wiki.gg/wiki/Fatum"),
    w("striga", "Striga", "Empaleur", "medium", ["fire", "air"], 4, { damage: 80, crit: 1.4, stun: "élevé", ads: 30, hip: 30, rof: 0.6, reload: 3.6, mag: 7, reserve: 43, mobility: "très haute" },
      ["Projectile en cloche, sans chute de dégâts avec la distance. M1 : +100 % contre un mineur étourdi, +25 % contre un majeur étourdi.", "M2 : après 0,5 s de vol, le pieu explose (30 dégâts) et brûle à +25 %.", "M3 : un critique électrocute les ennemis proches. Table des éléments : chaîne 30 % puis 15 %.", "Depuis la 1.0, hors accès anticipé, Striga est une arme de fin de partie. L'accès anticipé la trouvait chez le Collectionneur."],
      {
        burn: { from: 2, bead: true, mag: { 1: 0, 2: 0.25, 3: 0.25 } },
        shock: { from: 3, bead: true, first: 0.3, second: 0.15 },
      },
      "Fin de partie hors accès anticipé. Ancien emplacement : cave du Collectionneur.", "https://witchfire.wiki.gg/wiki/Striga"),
    w("rotweaver", "Rotweaver", "Pistolet-mitrailleur", "close", ["earth"], 4, { damage: 8, crit: 1.1, stun: "faible", ads: 11, hip: 10, rof: 15.1, reload: 3.3, mag: 60, reserve: 480, mobility: "très haute" },
      ["M1 : les tirs pourrissent. La jauge de rafale monte le tick de 5 à 8 en base. Même 1 dégât de balle suffit à lancer le malus : la portée pratique dépasse les 11 m affichés.", "M2 : une mort par Putréfaction rend 7 balles dans le chargeur, sans les prendre dans la réserve. Toute source de Putréfaction compte, pas seulement les balles.", "M3 : des kystes poussent sur les pourris et, tirés, répandent le malus."],
      { decay: { from: 1, bead: true, profile: "rotweaver" } },
      "Salle à manger de la Tour du Lamentin, sur l'autel du Prophète. La tour s'ouvre au Gnosis IV. Récupérable sans tuer le Prophète.", "https://witchfire.wiki.gg/wiki/Rotweaver"),
    w("judgment", "Judgment", "Fusil à pompe", "close", ["earth", "water"], 4, { damage: 140, crit: 1.1, stun: "élevé", ads: 7, hip: 7, rof: 1.3, reload: 0.6, mag: 6, reserve: 24, mobility: "moyenne", unwieldy: "shotgun" },
      ["Pompe lourde Terre + Eau. Putréfaction de la table : 5 par tick, 15 ticks, 75 au total en base."],
      { decay: { from: 1, bead: true, profile: "judgment" } },
      "Banc renversé du sanctuaire, après le labyrinthe de Witch Mountain.", "https://witchfire.wiki.gg/wiki/Judgment"),
    w("tribunal", "Tribunal", "Fusil à pompe", "close", ["air"], 5, { damage: 160, crit: 1.1, stun: "très élevé", ads: 7, hip: 7, rof: 1.6, reload: 2.5, mag: 3, reserve: 42, mobility: "très haute", unwieldy: "shotgun", pellets: "12 plombs" },
      ["Trois canons. Un dash ou une glissade, arme en main, charge un canon. Le tir chargé envoie une chaîne égale à 50 % des dégâts du tir. Ce n'est pas le malus Choc : les perles de malus ne le changent pas.", "M2 : recharger à la main charge aussi le coup suivant.", "M3 : un surkill chargé fait 50 dégâts autour et pose un Choc de 30 %, celui-là sensible aux perles.", "Tirer coûte de l'endurance. La perle Short Range retire ce coût. Viser, s'accroupir ou glisser resserre les 12 plombs."],
      { shock: { from: 3, bead: true, first: 0.3, second: 0.15, reliable: 0.3, note: "Seul le surkill du Mysterium III pose le Choc, à 30 %. La chaîne du canon chargé est un dégât à part, 50 % du tir, et elle ignore les perles." } },
      "Récompense du Tourment VI, lancé à l'étude profane. Le wiki ne publie pas de palier de Gnosis : le 5 évite seulement de le proposer en début de partie.", "https://witchfire.wiki.gg/wiki/Tribunal"),
  ];

  const demonic = [
    d("falling-star", "Falling Star", "Lance-grenades", [], 2, { damage: 250, crit: 1, stun: "moyen", ads: 30, hip: 30, rof: 1, reload: 2.7, mag: 6, reserve: 14 },
      ["Dégâts de zone bruts. Les armes démoniaques n'ont pas de Mysterium."],
      {}, "Recherche, 10 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Falling_Star"),
    d("vulture", "Vulture", "Arbalète", [], 2, { damage: 200, crit: 1.5, stun: "élevé", ads: 24, hip: 20, rof: 1, reload: 1.5, mag: 5, reserve: 10 },
      ["Coup de grâce à 200 dégâts et 150 % de critique. Munitions rares : à garder pour un élite ou un boss."],
      {}, "Recherche, 10 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Vulture"),
    d("whisper", "Whisper", "Pistolet étourdissant", [], 2, { damage: 220, crit: 1, stun: "très élevé", ads: 20, hip: 20, rof: 1.2, reload: 2.7, mag: 3, reserve: 17 },
      ["220 dégâts et l'étourdissement le plus haut du catalogue. Ouvre les fenêtres de mêlée et les bonus contre cibles étourdies (Striga M1)."],
      {}, "Recherche, 10 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Whisper"),
    d("soul-eater", "Soul Eater", "Canon à main", [], 4, { damage: 145, crit: 1.14, stun: "élevé", ads: 19, hip: 14, rof: 2.7, reload: 2, mag: 12, reserve: 24 },
      ["Canon démoniaque. Dans la Trinité, tirer un point faible créé par Heart Eater gagne 24 % et lâche une onde étourdissante."],
      {}, "Trois orbes latents du Marshland, à l'apothicaire.", "https://witchfire.wiki.gg/wiki/Soul_Eater"),
    d("tempest", "Tempest", "Rayon", ["air", "earth"], 4, { damage: 13, crit: 1.3, stun: "très faible", ads: 24, hip: 20, rof: 10, reload: 2.5, mag: 40, reserve: 120 },
      ["Rayon Air + Terre. Ouvre ces deux arcanes sans que le wiki publie un tick de Putréfaction ou un pourcentage de chaîne."],
      {}, "Recherche, 40 witchfire, 50 de temps, Gnosis IV.", "https://witchfire.wiki.gg/wiki/Tempest"),
    d("heart-eater-standin", "Heart Eater", "Canon à main", ["air"], 6, { damage: 53, crit: 1.14, stun: "très élevé", ads: 19, hip: 14, rof: 1.8, reload: 2.5, mag: 6, reserve: 84, standard: true },
      ["Étourdissement très élevé. Torment VIII. Pièce de la Trinité avec Corpse Eater et Soul Eater."],
      {}, "Tourment VIII, étude profane.", "https://witchfire.wiki.gg/wiki/Heart_Eater"),
  ];

  const melee = [
    meleeWeapon("fist", "Fist", 0, { damage: 20, charged: 70, special: 50, stunnedCharged: 300, stunnedSpecial: 100, reach: 4 },
      ["Coup de poing. Le premier coup chargé consomme la moitié de la charge, l'uppercut l'autre moitié.", "Il faut une charge pleine pour armer le coup chargé.", "Sur un étourdi : 300 puis 100. La perle de charge de mêlée peut enchaîner le premier coup, jusqu'à 900 cités.", "Allonge d'environ 3 à 4 m. L'uppercut peut viser une autre cible."],
      "Arme de mêlée de départ.", "https://witchfire.wiki.gg/wiki/Fist"),
    meleeWeapon("katar", "Katar", 1, { damage: 20, charged: 100, special: 100, stunnedCharged: 400, stunnedSpecial: 200, reach: 8 },
      ["Estoc chargé à 100. Le bond en glissade porte à environ 28 m et frappe aussi à 100.", "Sur un étourdi : 400 au chargé, 200 au bond.", "Le bond ne part que s'il y a une cible, et il ne s'annule plus une fois lancé."],
      "Deux orbes latents de la côte écarlate, à l'apothicaire.", "https://witchfire.wiki.gg/wiki/Katar"),
    meleeWeapon("morning-star", "Morning Star", 2, { damage: 20, charged: 200, special: 200, stunnedCharged: 600, stunnedSpecial: 400, reach: 7 },
      ["Coup chargé à 200, avec un balayage jusqu'à 100 selon la distance.", "Sur un étourdi : 600 sur la cible, jusqu'à 200 au balayage.", "Spécial : s'accroupir en l'air. Onde d'environ 7 m, 60 à 200, ou 120 à 400 sur des étourdis.", "La charge est dépensée même si personne n'est dans la zone."],
      "Salle à côté de la structure verte, en descendant le puits du coffre-fort de Velmorne.", "https://witchfire.wiki.gg/wiki/Morning_Star"),
    meleeWeapon("buckler", "Buckler", 3, { damage: 20, charged: 30, special: 60, reach: 0 },
      ["Maintenir la mêlée bloque les dégâts de face. Lever le bouclier avec un peu de charge blesse les proches de 30.", "La parade au bon moment renvoie un projectile perforant de 60, ou 72 en coup à la tête.", "La parade peut partir sans charge pleine. Le coût dépend de la force du coup reçu.", "Sans charge, les coups redeviennent des poings."],
      "Récompense du Tourment II, lancé à l'étude profane.", "https://witchfire.wiki.gg/wiki/Buckler"),
  ];

  const spells = [
    s("fireballs", "Fireballs", "light", ["fire"], 0, 25, "Trois boules de feu à tête chercheuse.",
      ["Brûlure d'une magnitude de +37,5 %, au-dessus du +25 % de base. Sensible aux perles."],
      { burn: { from: 1, bead: true, mag: { 1: 0.375, 2: 0.375, 3: 0.375 } } },
      "Recherche, Gnosis 0.", "https://witchfire.wiki.gg/wiki/Fireballs"),
    s("firebreath", "Firebreath", "light", ["fire"], 0, 20, "Un jet de feu qui blesse et recharge la mêlée.",
      ["Brûlure de base +25 %, faute d'exception publiée. Utile aussi pour remplir la charge de mêlée."],
      { burn: { from: 1, bead: true, mag: { 1: 0.25, 2: 0.25, 3: 0.25 } } },
      "Island of the Damned.", "https://witchfire.wiki.gg/wiki/Firebreath"),
    s("frost-cone", "Frost Cone", "light", ["water"], 0, 22, "Un cône de givre qui gèle tout sur son passage.",
      ["Gel de zone. Les gelés subissent +50 % de dégâts. Cette vulnérabilité ignore les perles. La perle Acute raccourcit le gel sans le renforcer."],
      { freeze: { from: 1, reliable: 1 } },
      "Recherche, 2 witchfire, Gnosis 0.", "https://witchfire.wiki.gg/wiki/Frost_Cone"),
    s("shockwave", "Shockwave", "light", [], 0, 15, "Une onde qui étourdit les mineurs et les majeurs épuisés.",
      ["Contrôle sans élément. 40 d'endurance, recharge rapide (15)."],
      {}, "Recherche, 5 witchfire, Gnosis 0.", "https://witchfire.wiki.gg/wiki/Shockwave"),
    s("winter-nail", "Winter Nail", "heavy", ["water"], 0, 0, "Une volée de stalactites. Elles gèlent à l'impact et restent fichées au sol.",
      ["Recharge affichée 0 : le sort se réarme par le jeu, pas par un long compteur. Gel de zone et pièges au sol."],
      { freeze: { from: 1, reliable: 0.9 } },
      "Shrouded Hermitorium.", "https://witchfire.wiki.gg/wiki/Winter_Nail"),
    s("blight-cyst", "Blight Cyst", "light", ["earth"], 1, 20, "Un kyste sur le décor ou un ennemi. Il explose seul, et plus fort si on le tire.",
      ["Petit kyste : 1 dégât par tick, 30 ticks. Gros kyste (tiré) : 5 par tick, 30 ticks, 150 au total."],
      { decay: { from: 1, bead: true, profile: "cyst" } },
      "Recherche, 5 witchfire, Gnosis I.", "https://witchfire.wiki.gg/wiki/Blight_Cyst"),
    s("ice-stiletto", "Ice Stiletto", "light", ["water"], 1, 18, "Un stylet de glace qui gèle la cible.",
      ["Gel à cible unique, recharge rapide. Idéal pour un élite que Hailstorm ou Oracle doit exécuter sous vulnérabilité +50 %."],
      { freeze: { from: 1, reliable: 1 } },
      "Recherche, 5 witchfire, Gnosis I.", "https://witchfire.wiki.gg/wiki/Ice_Stiletto"),
    s("lightning-bolt", "Lightning Bolt", "light", ["air"], 1, 17, "Un éclair qui repousse et électrocute.",
      ["Plus forte chaîne publiée : 60 % du tir puis 30 %. Recharge 17."],
      { shock: { from: 1, bead: true, first: 0.6, second: 0.3 } },
      "Recherche, 5 witchfire, Gnosis I.", "https://witchfire.wiki.gg/wiki/Lightning_Bolt"),
    s("stigma", "Stigma Diabolicum", "light", ["earth"], 1, 15, "Un kyste qui devient un point faible supplémentaire.",
      ["M1 : les tirs sur le kyste valent ×1,25, 20 s, trois charges au M3, portée de la ligne de vue.", "M2 : ×1,29, 25 s, et Putréfaction au contact (4 par tick, 63 ticks, 252 au total).", "M3 : ×1,35, 30 s. Tuer par la putréfaction ou par un tir sur le kyste rend de la charge."],
      { decay: { from: 2, bead: true, profile: "stigma" } },
      "Côte écarlate, derrière un mirage. Gnosis I et 2 500 pour dissiper.", "https://witchfire.wiki.gg/wiki/Stigma_Diabolicum"),
    s("cursed-bell", "Cursed Bell", "heavy", [], 2, 65, "Une cloche. La tirer sonne et étourdit les mineurs proches.",
      ["Contrôle de foule sans élément. À sonner soi-même en lui tirant dessus."],
      {}, "Recherche, 10 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Cursed_Bell"),
    s("iron-cross", "Iron Cross", "heavy", ["air"], 2, 100, "Une croix de fer qui foudroie et attache les ennemis proches.",
      ["Chaîne 30 % puis 15 %. Recharge lente (100) : c'est un sort de groupe, pas un sort qu'on lance au passage."],
      { shock: { from: 1, bead: true, first: 0.3, second: 0.15 } },
      "Recherche, 8 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Iron_Cross"),
    s("stormball", "Stormball", "light", ["air"], 2, 35, "Une boule de foudre qui électrocute le long de sa route. Aucun coût d'endurance.",
      ["Chaîne 37,5 % puis 18,75 %. Dure jusqu'à un obstacle ou 20 s.", "M2 : après deux secondes elle gonfle.", "M3 : elle explose sur un obstacle."],
      { shock: { from: 1, bead: true, first: 0.375, second: 0.1875 } },
      "Recherche, 5 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Stormball"),
    s("burning-stake", "Burning Stake", "heavy", ["fire"], 3, 60, "Un bûcher qui enflamme. Les blesser le charge. À plein, il explose.",
      ["M1 : 25 s, 20 m, brûlure +25 %.", "M2 : 30 s, 25 m, brûlure +31,25 %.", "M3 : 35 s, 30 m, brûlure +37,5 %. Les morts chargent aussi le bûcher, d'où les explosions en chaîne.", "Coût : 60 d'endurance."],
      { burn: { from: 1, bead: true, mag: { 1: 0.25, 2: 0.3125, 3: 0.375 }, aoe: true } },
      "Sous le pont de la cascade, Irongate Castle, derrière un mirage. Gnosis III et 15 000.", "https://witchfire.wiki.gg/wiki/Burning_Stake"),
    s("ice-sphere", "Ice Sphere", "heavy", ["water"], 3, 60, "Une sphère qui protège le lanceur et gèle qui entre dedans.",
      ["Survie et gel de contact. 60 d'endurance."],
      { freeze: { from: 1, reliable: 0.85 } },
      "Recherche, 12 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Ice_Sphere"),
    s("rotten-fiend", "Rotten Fiend", "heavy", ["fire", "earth"], 3, 55, "Relève un grenadier qui attaque ses anciens alliés.",
      ["Putréfaction très longue : 5 par tick, 82 ticks, 410 au total en base. Les ticks se rafraîchissent tant que le familier vit. L'attunement Feu ouvre les arcanes de Feu sans poser, à lui seul, la Brûlure chiffrée du wiki."],
      { decay: { from: 1, bead: true, profile: "fiend" } },
      "Recherche, 12 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Rotten_Fiend"),
    s("cornucopia", "Cornucopia", "heavy", [], 3, 100, "La dernière balle se régénère. Le rechargement manuel reste possible. Ignore les armes démoniaques.",
      ["Sort de munitions, pas d'élément."],
      {}, "Recherche, 12 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Cornucopia"),
    s("miasma", "Miasma", "heavy", ["earth"], 4, 65, "Un encensoir qui pourrit autour de lui. Le tirer avant l'arrêt prolonge l'effet.",
      ["Haut de fourchette cité : 15 dégâts par tick, 52 ticks, 428 au total en base. La table a été mesurée avec +50 % de durée élémentaire."],
      { decay: { from: 1, bead: true, profile: "miasma" } },
      "Witch Mountain.", "https://witchfire.wiki.gg/wiki/Miasma"),
    s("pyre-skull", "Pyre Skull", "light", ["fire"], 4, 0, "Un crâne brûlant qui éclate puis revient en tourelle de flammes.",
      ["Recharge 0. M3 : chaque kill multiplie la magnitude de brûlure, jusqu'à cinq kills (+56,25 % avant perles)."],
      { burn: { from: 1, bead: true, mag: { 1: 0.25, 2: 0.25, 3: 0.25 }, note: "Le M3 monte après les kills : +31 %, +37 %, +44 %, +50 %, +56 % avant perles." } },
      "Marshland.", "https://witchfire.wiki.gg/wiki/Pyre_Skull"),
    s("twinshade", "Twinshade", "light", [], 4, 20, "Une épée ou un marteau spectral, selon la vie de l'ennemi.",
      ["Mêlée magique sans élément."],
      {}, "Witch Mountain.", "https://witchfire.wiki.gg/wiki/Twinshade"),
  ];

  const relics = [
    r("severed-ear", "Severed Ear", [], 0, "Recharger lâche une onde qui repousse.", ["Contrôle de proximité, sans élément."], {}, "Shrouded Hermitorium.", "https://witchfire.wiki.gg/wiki/Severed_Ear"),
    r("biting-tongue", "Biting Tongue", ["water"], 0, "Briser une barrière lâche une onde de gel.", ["Gel conditionnel, quand une barrière tombe."], { freeze: { from: 1, reliable: 0.4 } }, "Shrouded Hermitorium.", "https://witchfire.wiki.gg/wiki/Biting_Tongue"),
    r("kirfane", "Kirfane", ["air"], 1, "Après une série de tirs, un éclair saute entre les ennemis proches.",
      ["M1 : 30 tirs. M2 : 25 tirs et 2 % de chance par tir. M3 : 20 tirs, 3 %, et un sort léger garantit l'arc au tir suivant.", "La chaîne ne diminue pas d'un saut à l'autre et ignore les perles de malus. Depuis la 0.9, la cible initiale reçoit un court Choc.", "Exemples de dégâts d'éclair selon le tir : 8 → 20, 25 → 44, 80 → 48, 160 → 96."],
      { shock: { from: 1, bead: false, qualitative: true, reliable: 0.7, note: "Éclair après une rafale. Pas le même calcul que la chaîne d'un Choc classique." } },
      "Dernière salle du coffre-fort de l'île des Damnés. Gnosis I et 2 500.", "https://witchfire.wiki.gg/wiki/Kirfane"),
    r("parasite", "Parasite", ["earth"], 2, "Maudit l'ennemi le plus proche avec la Putréfaction.",
      ["M1 : 10 m, 10 s de récupération. M2 : 12 m, 8 s, le malus saute en montant (2, 3, 5, 6, 8, 9, puis 10 par tick).", "M3 : 15 m, 6 s, 30 % de chance de se dédoubler.", "Les perles ne changent pas ces ticks. Le feu, lui, les multiplie encore via la formule Brûlure × Putréfaction. Pas de ligne de vue requise."],
      { decay: { from: 1, bead: false, profile: "parasite" } },
      "Égouts de Velmorne, derrière un mirage. Gnosis II et 7 500.", "https://witchfire.wiki.gg/wiki/Parasite"),
    r("book-of-serpents", "Book of Serpents", ["earth"], 3, "Quiconque blesse le porteur subit la Putréfaction.",
      ["7 dégâts par tick, 20 ticks, 140 au total. Insensible aux perles. Se cumule si le Préyer est touché plusieurs fois."],
      { decay: { from: 1, bead: false, profile: "book" } },
      "Recherche, 20 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Book_of_Serpents"),
    r("eye-of-the-madwoman", "Eye of the Madwoman", ["air"], 3, "Frappe d'un éclair céleste tout ennemi proche de la mort.",
      ["Chaîne faible : 15 % puis 7,5 %. Peut prendre le dernier tick d'un Rotweaver, ce qui empêche le M2 de rendre des balles."],
      { shock: { from: 1, bead: true, first: 0.15, second: 0.075, reliable: 0.5 } },
      "Recherche, 17 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Eye_of_the_Madwoman"),
    r("braid", "Braid of a Seductress", ["water"], 3, "Une aura qui gèle le mineur qui blesse le porteur au corps à corps.",
      ["Gel défensif, réservé aux mineurs en mêlée."],
      { freeze: { from: 1, reliable: 0.45 } },
      "Irongate Castle.", "https://witchfire.wiki.gg/wiki/Braid_of_a_Seductress"),
    r("blood-banshee", "Blood of a Banshee", ["fire"], 4, "Les dégâts en trop font exploser la victime, qui enflamme les proches.",
      ["Brûlure de base +25 % sur cette explosion. Se combine avec une zone déjà en feu."],
      { burn: { from: 1, bead: true, mag: { 1: 0.25, 2: 0.25, 3: 0.25 }, reliable: 0.55, aoe: true } },
      "Recherche, 25 witchfire, Gnosis IV.", "https://witchfire.wiki.gg/wiki/Blood_of_a_Banshee"),
    r("painted-tooth", "Painted Tooth", ["fire"], 4, "Un critique sur une cible pleine vie l'enflamme.",
      ["Brûlure de base +25 %. Demande de viser le premier coup sur une cible intacte."],
      { burn: { from: 1, bead: true, mag: { 1: 0.25, 2: 0.25, 3: 0.25 }, reliable: 0.6 } },
      "Recherche, 25 witchfire, Gnosis IV.", "https://witchfire.wiki.gg/wiki/Painted_Tooth"),
    r("scourge", "Scourge", [], 4, "Empêche un coup fatal en retirant l'endurance bonus. Se rafraîchit en regagnant la Focalisation.",
      ["Filet de sécurité sans élément."],
      {}, "Recherche, 25 witchfire, Gnosis IV.", "https://witchfire.wiki.gg/wiki/Scourge"),
  ];

  const rings = [
    ring("static-ring", "Static Ring", ["air"], 0, "La glissade laisse une étincelle de foudre qui électrocute les proches.",
      ["Chaîne 30 % puis 15 %. Se joue en glissade, pas en dash."],
      { shock: { from: 1, bead: true, first: 0.3, second: 0.15 } },
      "Shrouded Hermitorium.", "https://witchfire.wiki.gg/wiki/Static_Ring"),
    ring("crown-of-fire", "Crown of Fire", ["fire"], 2, "Le dash pose le Feu sur l'arme, brièvement.",
      ["M1 : 1 s. M2 : 1,1 s, et enflammer recharge un tiers du chargeur.", "M3 : 1,2 s, et un double dash triple la durée.", "Brûlure +25 %, sensible aux perles. Fonctionne sur une arme qui n'a pas le Feu, Rotweaver compris."],
      { burn: { from: 1, bead: true, mag: { 1: 0.25, 2: 0.25, 3: 0.25 } }, dash: true },
      "Recherche, 20 witchfire, Gnosis II.", "https://witchfire.wiki.gg/wiki/Crown_of_Fire"),
    ring("dynamo-ring", "Dynamo Ring", ["air"], 3, "Le dash électrocute le dernier ennemi touché par une arme à feu.",
      ["Pas de temps de recharge, mais il faut retoucher pour réarmer la marque.", "Chaîne 17,5 % puis 8,75 %.", "M1 : 15 dégâts. M2 : 20, et les kills s'empilent jusqu'à 3. M3 : 25, six cumuls, et la décharge explose. Cumuls cités : 31, 37, 43, 50, 56, 62."],
      { shock: { from: 1, bead: true, first: 0.175, second: 0.0875 }, dash: true },
      "Recherche, 20 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Dynamo_Ring"),
    ring("meteor-ring", "Meteor Ring", ["fire"], 3, "Les glissades durent plus longtemps et laissent un sillage de feu.",
      ["Brûlure de base au sol. Se joue en glissade, comme Static Ring."],
      { burn: { from: 1, bead: true, mag: { 1: 0.25, 2: 0.25, 3: 0.25 }, reliable: 0.7 }, slide: true },
      "Irongate Castle.", "https://witchfire.wiki.gg/wiki/Meteor_Ring"),
    ring("ring-of-excreta", "Ring of Excreta", ["earth"], 3, "Le dash laisse une bombe à retardement qui blesse et repousse.",
      ["Putréfaction : 3 par tick, 9 ticks, 27 au total en base. Le recul est le vrai outil de survie."],
      { decay: { from: 1, bead: true, profile: "excreta" }, dash: true },
      "Recherche, 20 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Ring_of_Excreta"),
    ring("ring-of-thorns", "Ring of Thorns", ["water"], 3, "Esquiver un coup de mêlée par un dash gèle l'attaquant. Le tuer avant le dégel crée parfois un orbe de munitions.",
      ["Gel défensif, sans temps de recharge cité. L'orbe de munitions est occasionnel."],
      { freeze: { from: 1, reliable: 0.55 }, dash: true },
      "Recherche, 20 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Ring_of_Thorns"),
    ring("ring-of-wings", "Ring of Wings", [], 3, "Permet de dasher en l'air.",
      ["Mobilité pure, sans élément. Le coffre-fort de la côte écarlate s'ouvre au Gnosis III."],
      { dash: true },
      "Coffre-fort de la côte écarlate.", "https://witchfire.wiki.gg/wiki/Ring_of_Wings"),
    ring("shadowmist-ring", "Shadowmist Ring", ["water"], 4, "Le dash change le porteur en brume et lui permet de traverser les ennemis.",
      ["M1 : 9 m. M2 : 10 m et 25 points de vie volés. M3 : 11 m, 35 points de vie, et 50 % de chance de geler.", "Le gel du M3 est la porte d'entrée des arcanes Freezing Gust et Shattered Soul."],
      { freeze: { from: 3, reliable: 0.5 }, dash: true },
      "Recherche, 23 witchfire, Gnosis IV.", "https://witchfire.wiki.gg/wiki/Shadowmist_Ring"),
    ring("ring-of-obedience", "Ring of Obedience", [], 4, "Un dash vers le dernier blessé le pousse dans l'axe du déplacement.",
      ["Positionnement, sans élément."],
      { dash: true },
      "Recherche, 20 witchfire, Gnosis IV.", "https://witchfire.wiki.gg/wiki/Ring_of_Obedience"),
  ];

  const fetishes = [
    f("mandrake", "Mandrake", 0, "Annule une mort pendant l'expédition. Rend des points de vie, recharge les sorts et accorde quelques secondes d'immunité.", "Côte écarlate.", "https://witchfire.wiki.gg/wiki/Mandrake", 3),
    f("belladonna", "Belladonna", 3, "Une aura qui bloque les petits coups et laisse passer les gros.", "Recherche, 17 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Belladonna", 2),
    f("bittersweet", "Bittersweet Nightshade", 3, "Chaque dégât subi lâche une forte onde de choc.", "Recherche, 17 witchfire, Gnosis III.", "https://witchfire.wiki.gg/wiki/Bittersweet_Nightshade", 1),
    f("monkshood", "Monkshood", 5, "Absorber un cristal de Manifestation donne un bouclier qui annule un coup.", "Coffre-fort d'Irongate Castle.", "https://witchfire.wiki.gg/wiki/Monkshood", 2),
    f("henbane", "Henbane", 4, "Augmente fortement l'effet des élixirs de soin.", "Recherche, 19 witchfire, Gnosis IV.", "https://witchfire.wiki.gg/wiki/Henbane", 2),
    f("balewort", "Balewort", 4, "Les kills lâchent des orbes de soin, d'autant plus près de la mort.", "Recherche, 19 witchfire, Gnosis IV.", "https://witchfire.wiki.gg/wiki/Balewort", 2),
    f("yew", "Yew", 4, "Les orbes de bouclier parfois lâchés par les ennemis donnent un bouclier temporaire.", "Witch Mountain.", "https://witchfire.wiki.gg/wiki/Yew", 2),
  ];

  const beads = [
    bead("health", "Health Bead I", "Stat", "Santé +10 %.", 0, {}, 1, "Shrouded Hermitorium."),
    bead("stamina", "Stamina Bead I", "Stat", "Endurance +20 %.", 0, { stamina: 2 }, 1, "Island of the Damned. Sang 15."),
    bead("dash-stamina", "Dash Stamina Bead", "Capacité", "Les dashs enchaînés coûtent moins d'endurance.", 0, { dash: 3 }, 1, "Côte écarlate. Chair 20, Sang 30."),
    bead("spell-recharge", "Spell Recharge Bead I", "Stat", "Recharge des sorts +20 %.", 0, { spells: 2 }, 1, "Côte écarlate. Sorcellerie 15."),
    bead("blessed-aim", "Blessed Aim Bead I", "Stat", "Visée bénie +15 %.", 0, { crit: 2 }, 1, "Côte écarlate. Foi 15."),
    bead("ammo-reserves", "Ammo Reserves Bead I", "Stat", "Réserves de munitions +20 %.", 0, { ammo: 2 }, 1, "Shrouded Hermitorium. Arsenal 20."),
    bead("healing", "Healing Bead I", "Stat", "Soins +25 %.", 0, { survival: 2 }, 1, "Island of the Damned. Esprit 15."),
    bead("ailment-power", "Ailment Power Bead I", "Sort", "Puissance des malus +25 % (×1,25).", 1, { ailment: "power" }, 0, "Island of the Damned. Sorcellerie 15."),
    bead("elemental-duration", "Elemental Duration Bead I", "Stat", "Durée élémentaire +25 %.", 1, { duration: 2 }, 1, "Côte écarlate. Sorcellerie 25."),
    bead("free-arcana", "Free Arcana Bead", "Arcane", "Dévoiler un arcane ne coûte plus de plumes.", 1, { arcana: 2 }, 1, "Coffre-fort de l'île. Esprit 40, Sorcellerie 20."),
    bead("long-range", "Long Range Bead", "Arme", "Les fusils de précision ne sont plus encombrants.", 2, { sniper: 4 }, 2, "Velmorne. Sang 20, Arsenal 40."),
    bead("acute-ailment", "Acute Ailment Bead", "Sort", "Malus plus courts et deux fois plus forts (×2). Avec Ailment Power : ×2,25, en addition des bonus.", 2, { ailment: "acute" }, 0, "Velmorne. Sorcellerie 30."),
    bead("resistance", "Resistance Bead", "Capacité", "+20 % de résistance sous 50 % de vie.", 2, { survival: 2 }, 1, "Plusieurs régions. Chair 30, Sang 20."),
    bead("quickdraw", "Quickdraw Bead", "Arme", "Changement d'arme beaucoup plus rapide.", 2, { swap: 2 }, 1, "Shrouded Hermitorium. Arsenal 25."),
    bead("short-range", "Short Range Bead", "Arme", "Les fusils à pompe ne sont plus encombrants.", 3, { shotgun: 4 }, 2, "Irongate Castle. Sang 15, Arsenal 30."),
    bead("light-charge", "Light Spell Charge Bead", "Sort", "Une charge de sort léger en plus.", 3, { spells: 3 }, 2, "Coffre-fort de la côte écarlate. Sang 15, Sorcellerie 35."),
    bead("blessed-fire", "Blessed Fire Bead", "Arme", "Les coups de visée bénie mettent le feu.", 3, { crit: 1 }, 1, "Coffre-fort de Velmorne. Arsenal 20, Foi 30."),
    bead("blessed-hits", "Blessed Hits Bead", "Arme", "Les coups de visée bénie font 50 % de dégâts en plus.", 3, { crit: 3 }, 2, "Plusieurs régions. Arsenal 20, Foi 40."),
    bead("crystal-spell", "Crystal Spell Bead", "Sort", "Les cristaux de witchfire rechargent les sorts selon leur taille.", 1, { spells: 2 }, 1, "Côte écarlate. Sorcellerie 25."),
    bead("immune-dash", "Immune Dash Bead", "Capacité", "Le dash coûte plus d'endurance et donne une immunité.", 3, { dash: 2, survival: 2 }, 2, "Irongate Castle. Sang 30, Foi 15."),
    bead("dash-range", "Dash Range Bead", "Capacité", "Distance de dash +50 %.", 2, { dash: 2 }, 1, "Velmorne. Chair 15, Sang 30."),
    bead("weapon-range", "Weapon Range Bead I", "Stat", "Portée des armes +10 %.", 0, { range: 1 }, 1, "Côte écarlate. Arsenal 15."),
  ];

  /* Totaux du wiki. La page Éléments précise que ces mesures incluent déjà +50 % de durée élémentaire.
     Clé : none | power | acute | both. Pour Koschei et Rotweaver, deux jauges. */
  const decayTables = {
    eye: { label: "All-Seeing Eye", rows: { none: [2, 30, 60], power: [3, 30, 90], acute: [5, 16, 80], both: [5, 16, 80] } },
    koschei: {
      label: "Koschei, essaim chargé (M3)",
      rows: { none: [7, 15, 105], power: [9, 15, 135], acute: [15, 8, 120], both: [16, 8, 128] },
      alt: { label: "Koschei, essaim non chargé", rows: { none: [5, 15, 75], power: [6, 15, 90], acute: [10, 8, 80], both: [11, 8, 88] } },
    },
    rotweaver: {
      label: "Rotweaver, jauge de rafale pleine",
      rows: { none: [8, 19, 152], power: [11, 19, 209], acute: [17, 10, 170], both: [20, 10, 200] },
      alt: { label: "Rotweaver, jauge vide", rows: { none: [5, 19, 95], power: [6, 19, 114], acute: [10, 10, 100], both: [11, 10, 110] } },
    },
    judgment: { label: "Judgment", rows: { none: [5, 15, 75], power: [6, 15, 90], acute: [10, 8, 80], both: [11, 8, 88] } },
    cyst: {
      label: "Blight Cyst, gros kyste tiré",
      rows: { none: [5, 30, 150], power: [6, 30, 180], acute: [11, 16, 176], both: [12, 16, 192] },
      alt: { label: "Blight Cyst, petit kyste", rows: { none: [1, 30, 30], power: [2, 30, 60], acute: [4, 16, 64], both: [5, 16, 80] } },
    },
    stigma: { label: "Stigma Diabolicum", rows: { none: [4, 63, 252], power: [5, 63, 315], acute: [9, 33, 297], both: [10, 33, 330] } },
    miasma: {
      label: "Miasma, encensoir tiré (haut de fourchette)",
      rows: { none: [15, 52, 428], power: [18, 52, 762], acute: [30, 42, 1080], both: [33, 42, 1212] },
    },
    fiend: { label: "Rotten Fiend", rows: { none: [5, 82, 410], power: [6, 82, 492], acute: [10, 78, 780], both: [11, 78, 858] } },
    book: { label: "Book of Serpents", rows: { none: [7, 20, 140], power: [7, 20, 140], acute: [7, 20, 140], both: [7, 20, 140] }, immune: true },
    parasite: {
      label: "Parasite après plusieurs sauts (plafond 10)",
      rows: { none: [10, 12, 120], power: [10, 12, 120], acute: [10, 12, 120], both: [10, 12, 120] },
      immune: true,
      note: "Les ticks sont infinis tant que la chaîne tient. Le total ci-dessus borne 12 ticks pour comparer, il ne vient pas d'une ligne du wiki. Le premier maillon ne vaut que 2.",
    },
    excreta: { label: "Ring of Excreta", rows: { none: [3, 9, 27], power: [4, 9, 36], acute: [7, 4, 28], both: [7, 4, 28] } },
  };

  const rules = [
    { id: "burn-decay", pair: ["fire", "earth"], name: "Brûlure + Putréfaction", effect: "Ticks de putréfaction renforcés.", formula: "tick × multiplicateur de brûlure × 1,5" },
    { id: "burn-freeze", pair: ["fire", "water"], name: "Brûlure + Gel", effect: "Une explosion de dégâts.", formula: "Le wiki ne publie pas le montant de l'explosion." },
    { id: "burn-shock", pair: ["fire", "air"], name: "Brûlure + Choc", effect: "Éclairs plus forts, et le tir lui-même augmente si les deux malus sont sur la cible.", formula: "tir × magnitude d'éclair × 2,1 × multiplicateur de brûlure, si le groupe brûle" },
    { id: "decay-freeze", pair: ["earth", "water"], name: "Putréfaction + Gel", effect: "La putréfaction dure plus longtemps.", formula: "Aucun coefficient chiffré." },
    { id: "decay-shock", pair: ["earth", "air"], name: "Putréfaction + Choc", effect: "Chaque tick de putréfaction émet un éclair.", formula: "Aucun pourcentage publié pour cet éclair-là." },
    { id: "freeze-shock", pair: ["water", "air"], name: "Gel + Choc", effect: "Les éclairs partent plus souvent.", formula: "Aucune fréquence chiffrée." },
  ];

  const arcana = {
    fire: ["Pyrolysis (+15 % / +25 % aux cibles en feu, elles se soignent en partie quand la brûlure s'éteint)", "Accelerant (+15 % / +25 % aux cibles en feu)", "Critical Burn (tout tir sur un brûlé compte comme un critique)", "Flashover (un critique qui tue un brûlé le fait exploser)", "Chaos Flame (10 % / 20 % de double dégât sur un brûlé)", "Rekindled (tuer un brûlé recharge les sorts de Feu)"],
    earth: ["Decay Echo (les ticks sont plus forts au début, le total reste le même)", "Necrosis (+20 % / +30 % aux ticks)", "Doomsday Clock (la putréfaction ne s'éteint plus, puis continue à 1 ou 2)", "Putrefaction (le dernier tick vole 20 % / 25 % de la vie max)", "Circle of Life (une mort par tick recharge les sorts de Terre)", "Memento Mori (un sort de Terre brouille les ennemis 4 à 5 s)"],
    air: ["Conductor (l'éclair transporte tous les malus de la source)", "Thunderbolt (+20 % aux éclairs)", "Extra Bolt (un éclair de plus)", "More Bolt Jumps (un saut de plus)", "Perun (les critiques produisent plus d'éclairs)", "Recharged (une mort par éclair recharge les sorts d'Air)"],
    water: ["Freezing Gust (en dégèlant, onde de gel de 7 m)", "Shattered Soul (le dégel inflige 20 % de la vie max)", "Cryovolcano (un gelé brisé explose pour la moitié des dégâts subis gelé)", "Pagophobia (+20 % de dégâts d'arme contre un gelé)", "Snowball (tuer un gelé envoie un nuage qui gèle un autre)", "Long Winter (les majeurs restent gelés 1 s de plus)"],
  };

  const prophecies = {
    fire: "Prophecy of Fire",
    earth: "Prophecy of Earth",
    air: "Prophecy of Air",
    water: "Prophecy of Water",
    crit: "Dead Eyes",
    guns: "Firearms, Destruction, Nimble Fingers",
  };

  const community = [
    {
      id: "reddit-rot-machine",
      name: "Machine à pourriture",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "rotweaver", secondary: "striga", demonic: "vulture", light: "stormball", heavy: "burning-stake", relic: "kirfane", fetish: "monkshood", ring: "crown-of-fire" },
      beadHint: ["ailment-power", "acute-ailment", "elemental-duration", "dash-stamina", "short-range"],
      tags: ["elementaire", "foules", "fin"],
      rotation: "Double dash pour tripler la fenêtre de Crown of Fire au M3, ou poser Burning Stake. Arroser au Rotweaver, jauge pleine. Stormball dans le groupe. Se replier : la putréfaction finit le travail. Garder Vulture pour un élite qui traverse la zone.",
      blurb: "Le feu ne sert qu'à multiplier les ticks de putréfaction. On arrose au Rotweaver, on pose le bûcher, puis on se replie : la zone finit le groupe.",
      sources: [
        { label: "Reddit — Strongest Build(s)", url: "https://www.reddit.com/r/Witchfire/comments/1pstzzg/strongest_builds_in_the_game/" },
        { label: "Reddit — Fire + Decay", url: "https://www.reddit.com/r/Witchfire/comments/1uovowf/give_me_ideas_for_fire_decay_loadouts/" },
      ],
    },
    {
      id: "youtube-best",
      name: "Super Rot",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "rotweaver", secondary: "striga", melee: "buckler", light: "stigma", heavy: "burning-stake", relic: "kirfane", fetish: "henbane", ring: "crown-of-fire" },
      beadHint: ["ailment-power", "acute-ailment", "elemental-duration", "free-arcana"],
      tags: ["elementaire", "foules", "boss", "fin"],
      anchor: true,
      rotation: "Arroser le groupe au Rotweaver : un seul plomb suffit pour que la putréfaction, multipliée par le feu, finisse la cible. Stigma sur le bouclier ou le gros que la rafale rate. Burning Stake au milieu : les ticks le font exploser plusieurs fois. Striga seulement pour les orbes de folie. Deux dashs si Crown of Fire est au Mysterium III. Buckler est là si un tir arrive de face ; la vidéo dit qu'on peut mettre une autre mêlée, elle ne sert presque pas.",
      blurb: "Un plomb de Rotweaver suffit : la putréfaction, multipliée par le feu du bûcher, finit la cible. Stigma rattrape ce que la rafale rate. Striga sert aux orbes de folie.",
      sources: [{ label: "YouTube — SeraphMax, The BEST Builds", url: "https://www.youtube.com/watch?v=HixifX5oE7Y" }],
    },
    {
      id: "yt-seraph-melee",
      name: "Bond du Katar",
      phase: "milieu",
      gnosis: 3,
      slots: { primary: "psychopomp", secondary: "hypnosis", melee: "katar", light: "firebreath", heavy: "burning-stake", relic: "biting-tongue", fetish: "belladonna", ring: "crown-of-fire" },
      beadHint: ["short-range", "dash-stamina", "stamina", "ammo-reserves"],
      tags: ["corps", "boss", "elementaire"],
      anchor: true,
      rotation: "Burning Stake pour allumer, Firebreath sur ce qui brûle déjà : un mineur moyen peut tomber d'un coup, et un kill au souffle rend la mêlée. Katar en bond, le kill recharge Psychopomp. Hypnosis seulement hors de portée du bond. Belladonna absorbe les petits coups ; quand elle casse, Biting Tongue lâche son onde. Crown of Fire tient parce que la mêlée rend l'endurance.",
      blurb: "Le bûcher allume, le souffle achève, et un kill au souffle rend la mêlée. Le bond du Katar tue et recharge Psychopomp.",
      sources: [{ label: "YouTube — SeraphMax, build de mêlée", url: "https://www.youtube.com/watch?v=HixifX5oE7Y" }],
    },
    {
      id: "yt-seraph-freeze",
      name: "Gel de Frostbite",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "frostbite", secondary: "hunger", melee: "morning-star", light: "stormball", heavy: "ice-sphere", relic: "painted-tooth", fetish: "henbane", ring: "dynamo-ring" },
      beadHint: ["blessed-aim", "blessed-hits", "blessed-fire", "free-arcana"],
      tags: ["distance", "boss", "elementaire"],
      anchor: true,
      rotation: "Rester dans Ice Sphere. Frostbite à distance, et sa ligne de gel au Mysterium III quand on recule avec un orbe latent. Hunger en tête sur ce qui est figé : les critiques s'empilent. Stormball pour le groupe, Morning Star si le manque de zone se fait sentir. Dynamo sur le dernier touché au moment du dash. Painted Tooth brûle un critique sur une cible pleine vie.",
      blurb: "On reste dans la sphère de glace. Frostbite fige de loin, Hunger critique ce qui est figé. Stormball et la masse couvrent le groupe.",
      sources: [{ label: "YouTube — SeraphMax, build de gel", url: "https://www.youtube.com/watch?v=HixifX5oE7Y" }],
    },
    {
      id: "yt-seraph-echo",
      name: "Echo en glissade",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "echo", secondary: "striga", melee: "fist", light: "stormball", heavy: "burning-stake", relic: "blood-banshee", fetish: "henbane", ring: "static-ring" },
      beadHint: ["short-range", "blessed-aim", "blessed-hits", "free-arcana"],
      tags: ["corps", "elementaire", "foules"],
      anchor: true,
      rotation: "Stormball et Burning Stake pour vider les mineurs. Glisser avec Echo sur les gros : le bonus de glissade et Static Ring, qui laisse une étincelle, font le travail de zone. Striga au-delà de la pompe, et pour allumer le bûcher. Le poing si quelque chose colle ; Morning Star est possible, mais la vidéo trouve la masse trop lente à sortir. Blood of a Banshee explose les dégâts en trop.",
      blurb: "Stormball et le bûcher vident les mineurs. On glisse avec Echo sur les gros : le bonus de glissade et l'étincelle de l'anneau font la zone.",
      sources: [{ label: "YouTube — SeraphMax, build Echo", url: "https://www.youtube.com/watch?v=HixifX5oE7Y" }],
    },
    {
      id: "yt-seraph-cricket",
      name: "Cricket sans pause",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "cricket", secondary: "hunger", melee: "katar", light: "stormball", heavy: "cursed-bell", relic: "kirfane", fetish: "henbane", ring: "crown-of-fire" },
      beadHint: ["stamina", "blessed-aim", "blessed-hits", "free-arcana"],
      tags: ["foules", "tir", "boss"],
      anchor: true,
      rotation: "Cursed Bell, puis Stormball. Cricket d'un étourdi à l'autre, un dash entre chaque kill : la cadence ne retombe pas et le chargeur se remplit. Deux dashs tiennent Crown of Fire, donc le feu est presque toujours là. Katar si l'endurance casse, pour la reprendre et relancer la chaîne. Hunger sur le prêtre, le familier, le boss. Kirfane ajoute des éclairs tant que Cricket tire.",
      blurb: "La cloche étourdit, Stormball suit, et Cricket passe d'un étourdi à l'autre avec un dash entre chaque kill. La cadence ne retombe pas, et le feu du dash reste allumé.",
      sources: [{ label: "YouTube — SeraphMax, build Cricket", url: "https://www.youtube.com/watch?v=HixifX5oE7Y" }],
    },
    {
      id: "yt-nenril-hunger",
      name: "Hunger aux critiques",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "hunger", secondary: "psychopomp", demonic: "whisper", melee: "katar", light: "shockwave", heavy: "ice-sphere", relic: "scourge", fetish: "balewort", ring: "shadowmist-ring" },
      beadHint: ["short-range", "spell-recharge", "light-charge", "health", "stamina"],
      tags: ["tir", "boss", "survie"],
      anchor: true,
      rotation: "Hunger en visée, la prophétie Dead Eyes en premier pour Cascade et Critical Chain. Ice Sphere autour du tireur, Shockwave si les mineurs collent. Psychopomp et Katar quand la cible est trop près pour le canon : le kill de mêlée rend des balles. Whisper pour étourdir ce qui traverse. Shadowmist pour traverser le groupe. Scourge et Balewort tiennent si la vie descend.",
      blurb: "Hunger en visée, la sphère de glace autour du tireur. Si la cible colle, Psychopomp et le Katar reprennent la main : le kill de mêlée rend des balles.",
      sources: [{ label: "YouTube — Nenril, Hunger Critical Build", url: "https://www.youtube.com/watch?v=9QsJvPx3rp0" }],
    },
    {
      id: "yt-nenril-flagellant",
      name: "Le flagellant",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "psychopomp", melee: "katar", light: "stigma", heavy: "burning-stake", relic: "scourge", fetish: "balewort" },
      beadHint: ["short-range", "stamina", "healing"],
      tags: ["survie", "corps", "boss", "notable"],
      anchor: true,
      rotation: "Psychopomp au contact, Stigma sur la cible qui compte, Burning Stake au sol. Scourge annule un coup fatal et augmente les dégâts quand la vie est basse. Balewort lâche plus d'orbes de soin sous la moitié des points de vie. Katar quand le M3 a rechargé la mêlée.",
      blurb: "Psychopomp au contact, Stigma sur la cible qui compte, bûcher au sol. Quand la vie baisse, Scourge annule un coup fatal et Balewort soigne. Un kill de mêlée rend des balles, un kill au fusil recharge le Katar.",
      sources: [{ label: "YouTube — Nenril, Psychopomp et Scourge", url: "https://www.youtube.com/watch?v=Wm0X9Wi1X3I" }],
    },
    {
      id: "yt-nenril-midas",
      name: "Midas béni",
      phase: "milieu",
      gnosis: 3,
      slots: { primary: "midas", melee: "fist", fetish: "bittersweet" },
      beadHint: ["blessed-fire", "blessed-aim", "blessed-hits"],
      tags: ["tir", "boss", "elementaire", "notable"],
      anchor: true,
      rotation: "Midas en visée. Blessed Fire met le feu sur les coups de visée bénie, donc le Mysterium II de l'arme n'a plus à porter la brûlure. Bittersweet lâche une onde de choc à chaque dégât subi.",
      blurb: "Midas en visée. La perle de feu béni allume les coups, donc le second palier de l'arme n'a plus à porter la brûlure. Bittersweet lâche une onde à chaque coup reçu.",
      sources: [{ label: "YouTube — Nenril, Midas DPS", url: "https://www.youtube.com/watch?v=EWR8q3Q4DD4" }],
    },
    {
      id: "yt-nenril-tribunal",
      name: "Verdict du Tribunal",
      phase: "fin",
      gnosis: 5,
      slots: { primary: "tribunal", melee: "fist", ring: "crown-of-fire" },
      beadHint: ["dash-stamina", "stamina", "short-range"],
      tags: ["tir", "corps", "elementaire", "notable"],
      anchor: true,
      rotation: "Dash ou glissade pour charger un canon, puis tirer. La chaîne vaut la moitié des dégâts du tir et n'est pas un Choc. Crown of Fire part sur le même dash. Short Range retire le coût d'endurance de la pompe. Au M3, un surkill chargé blesse les proches de 50 et leur pose un Choc de 30 %.",
      blurb: "Un dash ou une glissade charge un canon. Le tir envoie une chaîne égale à la moitié des dégâts, et le même dash allume l'anneau de feu. Cette chaîne n'est pas un Choc.",
      sources: [{ label: "YouTube — Nenril, Tribunal", url: "https://www.youtube.com/watch?v=t60Xtwp7O20" }, { label: "Wiki — Tribunal", url: "https://witchfire.wiki.gg/wiki/Tribunal" }],
    },
    {
      id: "yt-nenril-echo-ice",
      name: "Echo sur le gel",
      phase: "milieu",
      gnosis: 3,
      slots: { primary: "echo", melee: "fist", light: "frost-cone", heavy: "ice-sphere" },
      beadHint: ["short-range", "ammo-reserves"],
      tags: ["elementaire", "corps", "notable"],
      anchor: true,
      rotation: "Geler au cône ou dans la sphère, puis Echo : les plombs brûlent, et une cible gelée subit 50 % de dégâts en plus.",
      blurb: "On fige au cône ou dans la sphère, puis Echo. Les plombs brûlent, et une cible gelée subit moitié plus de dégâts.",
      sources: [{ label: "YouTube — Nenril, Echo feu et glace", url: "https://www.youtube.com/watch?v=KILALFb3RqA" }],
    },
    {
      id: "reddit-coward",
      name: "Le lâche efficace",
      phase: "milieu",
      gnosis: 3,
      slots: { primary: "duelist", secondary: "basilisk", demonic: "whisper", light: "stigma", heavy: "rotten-fiend", relic: "parasite", fetish: "yew", ring: "ring-of-thorns" },
      beadHint: ["light-charge", "acute-ailment", "spell-recharge"],
      tags: ["elementaire", "distance", "survie", "notable"],
      rotation: "Stigma sur plusieurs cibles, Basilisk pour allumer la lunette et garder la brûlure. Parasite pourrit le plus proche. Duelist à courte portée seulement avec une source de Feu déjà posée. Ring of Thorns si quelque chose colle au corps.",
      blurb: "On reste loin et on laisse les ticks travailler. Basilisk et les sorts posent le feu et la pourriture. Duelist ne sort qu'à courte portée, une fois le feu déjà là.",
      sources: [{ label: "Reddit — Fire + Decay", url: "https://www.reddit.com/r/Witchfire/comments/1uovowf/give_me_ideas_for_fire_decay_loadouts/" }],
    },
    {
      id: "reddit-banshee",
      name: "Boucle de la Banshee",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "fatum", secondary: "judgment", demonic: "vulture", light: "lightning-bolt", heavy: "burning-stake", relic: "blood-banshee", fetish: "yew", ring: "dynamo-ring" },
      beadHint: ["ailment-power", "elemental-duration", "dash-stamina", "short-range"],
      tags: ["elementaire", "foules", "fin"],
      rotation: "Bûcher au sol, éclair ou dash Dynamo, Fatum en double anneau pour poser un troisième malus. Les dégâts en trop de Blood of a Banshee rallument le groupe. Judgment apporte une putréfaction de contact.",
      blurb: "Bûcher au sol, un éclair ou un dash, puis Fatum pose un troisième malus. Les dégâts en trop de la Banshee rallument le groupe.",
      sources: [{ label: "Reddit — Fire + Decay", url: "https://www.reddit.com/r/Witchfire/comments/1uovowf/give_me_ideas_for_fire_decay_loadouts/" }],
    },
    {
      id: "reddit-shadowmist",
      name: "Brume qui dégèle",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "hailstorm", secondary: "hunger", demonic: "whisper", light: "ice-stiletto", heavy: "ice-sphere", relic: "braid", fetish: "mandrake", ring: "shadowmist-ring" },
      beadHint: ["elemental-duration", "dash-stamina", "long-range", "blessed-aim", "stamina"],
      tags: ["survie", "elementaire", "fin"],
      rotation: "Dash à travers le groupe avec Shadowmist au M3 (50 % de gel, 35 points de vie volés). Ice Stiletto sur l'élite. Tirer pendant le gel (+50 % de dégâts subis). Chercher en priorité les arcanes Freezing Gust et Shattered Soul : ce sont des arcanes, pas des sorts.",
      blurb: "On traverse le groupe dans la brume : gel et vol de vie. On tire pendant que la cible est figée, elle subit moitié plus.",
      sources: [{ label: "Reddit — Strongest Build(s)", url: "https://www.reddit.com/r/Witchfire/comments/1pstzzg/strongest_builds_in_the_game/" }],
    },
    {
      id: "reddit-echo-dynamo",
      name: "Echo, Dynamo, œil fou",
      phase: "fin",
      gnosis: 5,
      slots: { primary: "echo", secondary: "midas", demonic: "vulture", light: "fireballs", heavy: "burning-stake", relic: "eye-of-the-madwoman", fetish: "henbane", ring: "dynamo-ring" },
      beadHint: ["ailment-power", "short-range", "dash-stamina", "spell-recharge"],
      tags: ["elementaire", "corps", "fin"],
      rotation: "Echo à bout portant pour la brûlure des plombs, dash Dynamo sur la dernière cible touchée, Eye of the Madwoman sur les mourants. Midas tient la moyenne distance et nourrit le bûcher.",
      blurb: "Echo brûle à bout portant, le dash frappe la dernière cible touchée, l'œil fou ramasse les mourants. Midas tient la moyenne distance.",
      sources: [{ label: "Reddit — Strongest Build(s)", url: "https://www.reddit.com/r/Witchfire/comments/1pstzzg/strongest_builds_in_the_game/" }],
    },
    {
      id: "gamerant-air",
      name: "Ligne d'orage",
      phase: "milieu",
      gnosis: 2,
      slots: { primary: "hypnosis", secondary: "ricochet", demonic: "vulture", light: "lightning-bolt", heavy: "iron-cross", relic: "kirfane", fetish: "mandrake", ring: "static-ring" },
      beadHint: ["ailment-power", "blessed-aim", "spell-recharge", "long-range"],
      tags: ["elementaire", "distance", "notable"],
      rotation: "Lightning Bolt pour poser le plus gros pourcentage de chaîne (60 %). Iron Cross sur le groupe. Hypnosis en tirs parfaits. Kirfane se charge tout seul sur la cadence de Ricochet. Static Ring en glissade pour un choc de plus.",
      blurb: "L'éclair pose la plus grosse chaîne, la croix de fer couvre le groupe, Hypnosis tient en tirs parfaits. Kirfane se charge sur la cadence de Ricochet.",
      sources: [{ label: "GameRant — combinaisons élémentaires", url: "https://gamerant.com/witchfire-all-elemental-combinations-effects/" }],
    },
    {
      id: "gamerant-water",
      name: "Ligne de grêle",
      phase: "milieu",
      gnosis: 3,
      slots: { primary: "hailstorm", secondary: "hunger", demonic: "whisper", light: "ice-stiletto", heavy: "ice-sphere", relic: "braid", fetish: "mandrake", ring: "ring-of-thorns" },
      beadHint: ["long-range", "elemental-duration", "blessed-aim", "stamina"],
      tags: ["distance", "survie", "boss"],
      rotation: "Geler avec Ice Stiletto, la sphère, ou le M3 de Hailstorm : trois critiques d'affilée fige la cible et les proches. Le gel vaut +50 % de dégâts subis, et Pagophobia en ajoute 20 % sur l'arme si vous le piochez. Hunger prépare son gel de M3 sur un chargeur parfait.",
      blurb: "On fige au stylet, à la sphère, ou au troisième critique de Hailstorm. Tout ce qui est gelé subit moitié plus. Hunger prépare son gel sur un chargeur parfait.",
      sources: [{ label: "GameRant — combinaisons élémentaires", url: "https://gamerant.com/witchfire-all-elemental-combinations-effects/" }],
    },
    {
      id: "snipers-survie",
      name: "Fusils de survie",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "hailstorm", secondary: "oracle", demonic: "whisper", light: "ice-stiletto", heavy: "ice-sphere", relic: "scourge", fetish: "mandrake", ring: "shadowmist-ring" },
      beadHint: ["long-range", "healing", "stamina", "resistance", "blessed-aim"],
      tags: ["survie", "distance", "boss", "notable"],
      anchor: true,
      cited: false,
      rotation: "Rester loin. Ice Stiletto ou la sphère si quelque chose approche : le gel ajoute 50 % de dégâts subis. Hailstorm enchaîne les critiques ; au troisième, l'onde de M3 fige la cible et les voisins. Oracle sur ce qui charge ou se cache : la visée ralentit, le tir traverse les murs, et deux secondes en visée donnent +50 % au coup suivant. Whisper si un ennemi colle. Shadowmist pour traverser le groupe. La perle Long Range retire le coût d'endurance des deux fusils.",
      blurb: "On reste loin. Hailstorm fige au troisième critique d'affilée. Oracle ralentit, tire à travers les murs, et frappe plus fort si la visée tient. La sphère couvre, Scourge annule un coup fatal.",
      sources: [
        { label: "Wiki — Hailstorm", url: "https://witchfire.wiki.gg/wiki/Hailstorm" },
        { label: "Wiki — Oracle", url: "https://witchfire.wiki.gg/wiki/Oracle" },
        { label: "Steam — les fusils de précision", url: "https://steamcommunity.com/app/3156770/discussions/0/572668060971868684/" },
        { label: "YouTube — Nenril, trois fusils", url: "https://www.youtube.com/watch?v=7UPClbqX6AA" },
      ],
    },
    {
      id: "cornucopia-psychopomp",
      name: "Dernière balle",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "psychopomp", secondary: "frostbite", demonic: "falling-star", melee: "katar", light: "shockwave", heavy: "cornucopia", relic: "scourge", fetish: "mandrake", ring: "ring-of-wings" },
      beadHint: ["short-range", "stamina", "ammo-reserves", "blessed-aim", "healing"],
      tags: ["tir", "corps", "boss"],
      anchor: true,
      rotation: "Poser Cornucopia avant d'engager. Psychopomp à bout portant tant que la corne tient : la dernière balle revient dans le chargeur. Au M3, un kill recharge la mêlée. Katar chargé, ou en bond pendant une glissade, finit la cible : au M1 ce kill rend jusqu'à la moitié du chargeur. Shockwave si les mineurs collent. Frostbite pour ce qui est hors de portée de la pompe. Falling Star sur un boss, le plus loin possible.",
      blurb: "Cornucopia fait revenir la dernière balle, donc chaque tir peut relancer l'arcane. Un kill au troisième palier de Psychopomp recharge le Katar, et ce kill rend des balles.",
      sources: [
        { label: "Reddit — Cornucopia + Final Bullet", url: "https://www.reddit.com/r/Witchfire/comments/1m1w6i4/try_this_build_cornucopia_final_bullet/" },
        { label: "Wiki — Cornucopia", url: "https://witchfire.wiki.gg/wiki/Cornucopia" },
        { label: "Wiki — Psychopomp", url: "https://witchfire.wiki.gg/wiki/Psychopomp" },
        { label: "Wiki — Katar", url: "https://witchfire.wiki.gg/wiki/Katar" },
        { label: "Steam — armes sans élément", url: "https://steamcommunity.com/app/3156770/discussions/0/728028631117438547/" },
      ],
    },
    {
      id: "cricket-crown",
      name: "Cadence couronnée",
      phase: "milieu",
      gnosis: 3,
      slots: { primary: "cricket", secondary: "angelus", demonic: "falling-star", light: "stormball", heavy: "cursed-bell", relic: "kirfane", fetish: "mandrake", ring: "crown-of-fire" },
      beadHint: ["dash-stamina", "stamina", "ammo-reserves", "spell-recharge", "ailment-power"],
      tags: ["tir", "foules", "elementaire", "notable"],
      anchor: true,
      rotation: "Dasher pour poser le feu de Crown of Fire sur Cricket, deux fois si l'anneau est au M3. Vider Cricket dans le groupe en feu. Stormball le long de la ligne pour le choc. Angelus si la cible est trop loin pour la rafale. Cursed Bell si un groupe de mineurs doit s'arrêter. Falling Star pour un élite qu'on ne veut pas approcher.",
      blurb: "Le dash allume Cricket. On vide la rafale dans le groupe en feu, et la boule d'orage pose le choc le long de la ligne.",
      sources: [
        { label: "Steam — armes sans élément", url: "https://steamcommunity.com/app/3156770/discussions/0/728028631117438547/" },
        { label: "Wiki — Cricket", url: "https://witchfire.wiki.gg/wiki/Cricket" },
        { label: "Wiki — Crown of Fire", url: "https://witchfire.wiki.gg/wiki/Crown_of_Fire" },
      ],
    },
    {
      id: "trinity",
      name: "Trinité des revolvers",
      phase: "fin",
      gnosis: 6,
      slots: { primary: "corpse-eater", secondary: "heart-eater-standin", demonic: "soul-eater", light: "stigma", heavy: "burning-stake", relic: "parasite", fetish: "henbane", ring: "crown-of-fire" },
      beadHint: ["ailment-power", "quickdraw", "elemental-duration", "blessed-aim"],
      tags: ["elementaire", "boss", "fin"],
      rotation: "Tenir les trois revolvers au Mysterium III pour passer de Schizm à Trinity. Viser le point faible de Heart Eater. La putréfaction citée se propage. Crown of Fire sur un dash pour multiplier ce tick. Le changement d'arme rapide est le geste central.",
      blurb: "Les trois revolvers au troisième palier passent de Schizm à Trinity. On vise le point faible, la putréfaction se propage, un dash multiplie le tick.",
      sources: [
        { label: "Wiki — Corpse Eater", url: "https://witchfire.wiki.gg/wiki/Corpse_Eater" },
        { label: "Wiki — Soul Eater", url: "https://witchfire.wiki.gg/wiki/Soul_Eater" },
      ],
    },
    {
      id: "yt-seraph-rex",
      name: "Rechargements explosifs",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "psychopomp", secondary: "hangfire", demonic: "falling-star", melee: "katar", light: "firebreath", heavy: "burning-stake", relic: "severed-ear", fetish: "henbane", ring: "static-ring" },
      beadHint: ["free-arcana", "blessed-hits", "short-range", "quickdraw"],
      tags: ["corps", "foules", "boss"],
      anchor: true,
      rotation: "Tirer au Hangfire, dasher pour sortir les sigils d'âme, recharger pour les faire sauter. Severed Ear fait la même chose au rechargement. Quickdraw enchaîne sur Psychopomp tant que la cible est étourdie. Firebreath sur le bûcher déjà allumé : un kill au souffle rend le Katar, un kill au Katar rend Psychopomp, un kill au fusil rend le Katar. Falling Star sur ce qu'on ne veut pas approcher. Static Ring en glissade. La perle d'économie de munitions citée n'est pas au rosaire.",
      blurb: "Un tir de Hangfire, un dash, et le rechargement fait sauter les sigils d'âme. On enchaîne sur Psychopomp tant que la cible est étourdie. Le souffle sur le bûcher rend la mêlée, et les kills se rendent les balles et le Katar.",
      sources: [{ label: "YouTube — SeraphMax, trois builds de plus", url: "https://www.youtube.com/watch?v=dhokPOIdeRI" }],
    },
    {
      id: "yt-seraph-stacks",
      name: "Chargeur intact",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "hunger", secondary: "nemesis", demonic: "vulture", melee: "fist", light: "stormball", heavy: "burning-stake", relic: "painted-tooth", fetish: "henbane", ring: "dynamo-ring" },
      beadHint: ["blessed-aim", "blessed-hits", "free-arcana"],
      tags: ["tir", "boss", "distance"],
      anchor: true,
      rotation: "Empiler les tirs en tête sans recharger Hunger. Les arcanes de rechargement en glissade, en dash et en chaîne critique tiennent le chargeur. Nemesis jusqu'à la porte du boss, puis on relâche Hunger. Dynamo étourdit au dash. Painted Tooth brûle ces critiques en tête. Stormball et le bûcher couvrent le groupe. Le poing étourdit quand le tir ne le fait pas. Vulture sur un élite. La perle qui garde les munitions n'est pas au rosaire.",
      blurb: "On empile les tirs en tête de Hunger sans recharger. Nemesis tient jusqu'à la porte du boss, puis on relâche le chargeur. Le dash étourdit, Painted Tooth brûle ces critiques, le poing couvre le reste.",
      sources: [{ label: "YouTube — SeraphMax, trois builds de plus", url: "https://www.youtube.com/watch?v=dhokPOIdeRI" }],
    },
    {
      id: "yt-seraph-infinite",
      name: "Gel infini",
      phase: "fin",
      gnosis: 4,
      slots: { primary: "hypnosis", secondary: "fatum", melee: "fist", light: "stormball", heavy: "burning-stake", relic: "kirfane", fetish: "henbane", ring: "crown-of-fire" },
      beadHint: ["free-arcana", "blessed-hits", "blessed-aim"],
      tags: ["elementaire", "foules", "tir"],
      anchor: true,
      rotation: "Tuer au Fatum, recharger une fois, et garder le chargeur si l'anneau d'Eau est sorti. On ne recharge plus : le gel reste, le dash de Crown of Fire pose le feu dessus, et le gel cassé fait le travail. On ne recharge pas Hypnosis non plus, pour ne pas casser la série de tirs parfaits. Kirfane suit la cadence. Stormball et le bûcher pour le groupe. Le poing si ça colle. La perle d'endurance des sigils d'âme et celle qui garde les munitions ne sont pas au rosaire.",
      blurb: "On tue au Fatum, on recharge une fois, et si le gel sort on ne recharge plus. Le dash pose le feu sur la glace. Hypnosis garde sa série de tirs parfaits, Kirfane suit la cadence.",
      sources: [{ label: "YouTube — SeraphMax, trois builds de plus", url: "https://www.youtube.com/watch?v=dhokPOIdeRI" }],
    },
    {
      id: "wiki-hangfire",
      name: "Hangfire tranquille",
      phase: "milieu",
      gnosis: 2,
      slots: { primary: "hangfire", secondary: "angelus", demonic: "vulture", melee: "fist" },
      beadHint: [],
      tags: ["notable"],
      anchor: true,
      rotation: "Hangfire ouvre à moyenne distance. Angelus tient la cadence ensuite ; Ricochet peut prendre sa place. Vulture ramasse ce qui dépasse. Le poing ferme le contact.",
      blurb: "Hangfire ouvre, Angelus tient la cadence, Vulture ramasse ce qui dépasse. Ricochet peut prendre la place d'Angelus. Le poing ferme le contact.",
      sources: [{ label: "Wiki — meilleures armes", url: "https://witchfire.wiki/guides/witchfire-best-weapons/" }],
    },
    {
      id: "steam-meteor",
      name: "Sillage de Cricket",
      phase: "milieu",
      gnosis: 3,
      slots: { primary: "cricket", melee: "fist", fetish: "belladonna", ring: "meteor-ring" },
      beadHint: ["dash-stamina", "stamina"],
      tags: ["notable"],
      anchor: true,
      rotation: "Glisser pour laisser le sillage de feu, et arroser dedans au Cricket. Belladonna absorbe les petits coups et laisse passer les gros. Le poing si quelque chose traverse l'aura.",
      blurb: "On glisse dans le sillage de feu, Cricket arrose dedans, Belladonna bloque les petits coups. Ça ne sert pas à tenir un siège.",
      sources: [{ label: "Steam — guide d'équipement", url: "https://steamcommunity.com/sharedfiles/filedetails/?id=3452118540" }],
    },
  ];

  function w(id, name, weaponType, range, elements, gnosis, stats, mysteria, applies, found, url) {
    return { id, name, slot: "weapon", weaponType, range, elements, gnosis, stats, mysteria, applies, found, url, demonic: false };
  }
  function meleeWeapon(id, name, gnosis, stats, notes, found, url) {
    return { id, name, slot: "melee", weaponType: "Mêlée", range: "melee", elements: [], gnosis, stats, mysteria: notes, applies: {}, found, url, demonic: false };
  }
  function d(id, name, weaponType, elements, gnosis, stats, mysteria, applies, found, url) {
    const standard = !!stats.standard;
    return { id, name, slot: standard ? "weapon" : "demonic", weaponType, range: standard ? "medium" : "demonic", elements, gnosis, stats, mysteria, applies, found, url, demonic: !standard };
  }
  function s(id, name, spellType, elements, gnosis, recharge, summary, mysteria, applies, found, url) {
    return { id, name, slot: spellType === "light" ? "light" : "heavy", spellType, elements, gnosis, recharge, summary, mysteria, applies, found, url, range: spellType };
  }
  function r(id, name, elements, gnosis, summary, mysteria, applies, found, url) {
    return { id, name, slot: "relic", elements, gnosis, summary, mysteria, applies, found, url };
  }
  function ring(id, name, elements, gnosis, summary, mysteria, applies, found, url) {
    return { id, name, slot: "ring", elements, gnosis, summary, mysteria, applies, found, url };
  }
  function f(id, name, gnosis, summary, found, url, safety) {
    return { id, name, slot: "fetish", elements: [], gnosis, summary, mysteria: [summary], applies: {}, found, url, safety };
  }
  function bead(id, name, kind, summary, gnosis, tags, utility, found) {
    return { id, name, slot: "bead", kind, summary, gnosis, tags, utility, found, elements: [], applies: {}, mysteria: [] };
  }

  root.WF_DATA = {
    EL, weapons, demonic, melee, spells, relics, rings, fetishes, beads, decayTables, rules, arcana, prophecies, community,
    sources: [
      { label: "Wiki — Éléments", url: "https://witchfire.wiki.gg/wiki/Elements" },
      { label: "Wiki — Armes", url: "https://witchfire.wiki.gg/wiki/Weapons" },
      { label: "Wiki — Sorts", url: "https://witchfire.wiki.gg/wiki/Spells" },
      { label: "Wiki — Objets magiques", url: "https://witchfire.wiki.gg/wiki/Magical_Items" },
      { label: "Wiki — Rosaire", url: "https://witchfire.wiki.gg/wiki/Rosary" },
      { label: "Wiki — Arcanes", url: "https://witchfire.wiki.gg/wiki/Arcana" },
      { label: "Wiki — Gnosis", url: "https://witchfire.wiki.gg/wiki/Gnosis" },
      { label: "Wiki — meilleures armes", url: "https://witchfire.wiki/guides/witchfire-best-weapons/" },
      { label: "Steam — guide d'équipement", url: "https://steamcommunity.com/sharedfiles/filedetails/?id=3452118540" },
      { label: "YouTube — SeraphMax, trois builds de plus", url: "https://www.youtube.com/watch?v=dhokPOIdeRI" },
    ],
  };
})(typeof window !== "undefined" ? window : globalThis);
